### PR TITLE
Fix build most build warnings + PHP 8 compat

### PR DESCRIPTION
**Pull request by remicollet**
This allow to build with 8.0.0beta2 without warning

(beta3 needed for test suite to pass)

### CODE REVIEW

**Comment by remicollet** [comment]
@nikic any idea why `zend_call_method` is case-sensitive in 8 ? 
can find any information about this ?

This change seems to fix this issue

```
-        zend_call_method_with_0_params(PROPERTY_ARG(stream), NULL, NULL, "isReadable", &zreadable);
+        zend_call_method_with_0_params(PROPERTY_ARG(stream), NULL, NULL, "isreadable", &zreadable);
```

**Comment by remicollet** [comment]
Using this PR and PHP_VERSION : **8.0.0beta2**

```
=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   17
---------------------------------------------------------------------

Number of tests :  196               196
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Tests passed    :  196 (100.0%) (100.0%)
---------------------------------------------------------------------
Time taken      :    1 seconds
=====================================================================

```

**Comment by nikic** [comment]
@remicollet It looks like zend_call_method was case sensitive in some cases, depending on whether one parameter is NULL or not. Now it's always case sensitive... I will take a look, it should probably not be case sensitive.

**Comment by remicollet** [comment]
> it should probably not be case sensitive.

+1

> I will take a look, 

Thanks

**Comment by nikic** [comment]
@remicollet It should be fixed by https://github.com/php/php-src/commit/55798e0e391d18d7e7d321c1149b12aa89d7d4ff.

**Comment by remicollet** [comment]
@nikic Thanks a lot, I confirm everything is now OK with PHP master

@jasny so PR ready (hack removed), test suite fails with beta2, but is OK with master (so will be with beta3)

**Comment by jasny** [comment]
@remicollet Thanks. I'll test it out and merge if ok.

**Review by jasny — APPROVED** [review]

**Pull request merged**
